# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pedigree Productions
email: james@pedigreepro.net
description: > # this means to ignore newlines until "baseurl:"
  Pedigree Productions makes sales catalogs for horse sales, bloodstock agents and a lot of other people. All thoroughbred pedigrees made to order. Contact for more information.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pedigreepro.net" # the base hostname & protocol for your site
tagline: We'll do everything in our power to help your horse shine in their best light.
twitter_username: pedigree_pro
github_username:  jekyll
facebook_username: pedigreepro
instagram_username: something
linkedin_username: pedigree-productions

# Build settings
markdown: kramdown
